version: "3.9"
services:
  lyric-app-nginx:
    image: nginx
    depends_on:
      - lyric-app-prod
    ports:
      - '8000:80'
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - go-network

  lyric-app-prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    ports:
      - '3000'
    depends_on:
      - lyric-mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 300s
    networks:
      - go-network

  lyric-mysql:
    image: mysql:8
    restart: "no"
    tty: true
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lyrics
    networks:
      - go-network

  lyric-pma:
    restart: "no"
    image: phpmyadmin/phpmyadmin
    ports:
      - '8001:80'
    environment:
      MYSQL_USERNAME: root
      PMA_HOST: lyric-mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - lyric-mysql
    networks:
      - go-network

  lyric-docs:
    build: 
      context: .
      dockerfile: Dockerfile
      target: docs
    restart: "no"
    ports:
      - 8002:8002
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
